version: "3.8"

services:
  db:
    image: docker.io/mariadb:11.1
    container_name: mariadb_container
    restart: always
    ports:
      - "3307:3306"
    expose:
      - 3306
    volumes:
      - ./db/data:/var/lib/mysql:z
      - ./db/init:/docker-entrypoint-initdb.d:z
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MARIADB_DATABASE=${DB_DATABASE}
      - MARIADB_USER=${DB_USER}
      - MARIADB_PASSWORD=${DB_PASSWORD}

  redis:
    image: docker.io/redis:latest
    container_name: redis_container
    restart: always
    expose:
      - 6379

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5000:5000"
    expose:
      - "5000"
    volumes:
      - ./app:/app:z
    environment:
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_ACCESS_SECRET_KEY=${JWT_ACCESS_SECRET_KEY}
      - JWT_REFRESH_SECRET_KEY=${JWT_REFRESH_SECRET_KEY}
      - JWT_REFRESH_EXPIRATION=3600
      - JWT_ACCESS_EXPIRATION=600
    depends_on:
      - db
      - redis
