version: "3.8"

services:
  db:
    image: docker.io/mysql:8.0
    container_name: mysql_container
    restart: always
    ports:
      - "3307:3306"
    expose:
      - 3306
    volumes:
      - ./db/data:/var/lib/mysql:z
      - ./db/init:/docker-entrypoint-initdb.d:z
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ./app:/app:Z
    ports:
      - "5000:5000"
    expose:
      - "5000"
    environment:
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - JWT_ACCESS_SECRET_KEY=${JWT_ACCESS_SECRET_KEY}
      - JWT_REFRESH_SECRET_KEY=${JWT_REFRESH_SECRET_KEY}
      - JWT_REFRESH_EXPIRATION=3600
      - JWT_ACCESS_EXPIRATION=600
    depends_on:
      - db
